"""Bundled catalog + benchmark data — the package is the source of truth.

``models.json`` / ``benchmarks.json`` / ``published_scores.json`` live here and ship
inside the wheel. Every front-end (the VS Code extension and any other MCP client)
consumes copies of these files; nothing reads them out of ``clients/vscode/``
anymore. The extension's build copies them in from here.

``models.json`` is regenerated by ``clients/vscode/scripts/generate-models.py``
(the litellm catalog); benchmark scores come from published online leaderboards
(``galaius-fetch-upstream`` → ``published_scores.json``). We never run our own paid
grounding eval — optional measured scores can be injected via ``GALAIUS_GROUNDING_JSON``.
"""

import json
import os
from importlib.resources import files
from pathlib import Path


class PackageData:
    """Read access to the JSON data bundled with the ``galaius`` package.

    Resolution for the dynamic blobs is uniform: an environment variable (set by
    a host such as the VS Code extension) wins, otherwise the bundled file.
    """

    MODELS = "models.json"
    BENCHMARKS = "benchmarks.json"
    PUBLISHED = "published_scores.json"
    SETTINGS = "settings.json"
    #: Snapshot of the MCP tool list (`galaius.server.core.tool_catalog`), for readers that list
    #: galaius's tools without importing its server.
    MCP_TOOLS = "mcp_tools.json"

    @classmethod
    def path(cls, name: str) -> Path:
        """Filesystem path to a bundled file (for read-modify-write dev tools)."""
        return Path(str(files("galaius.data") / name))

    @classmethod
    def read(cls, name: str) -> str | None:
        """Text content of a bundled file, or ``None`` when it is absent."""
        resource = files("galaius.data") / name
        return resource.read_text() if resource.is_file() else None

    @classmethod
    def models_raw(cls) -> str | None:
        """``models.json`` text: ``GALAIUS_MODELS_JSON`` env wins, else the bundled file."""
        return os.environ.get("GALAIUS_MODELS_JSON") or cls.read(cls.MODELS)

    @classmethod
    def models_data(cls) -> dict:
        """Parsed ``models.json`` (env or bundled); ``{}`` when missing or invalid."""
        raw = cls.models_raw()
        if not raw:
            return {}
        try:
            return json.loads(raw)
        except (ValueError, TypeError):
            return {}

    @classmethod
    def settings_data(cls) -> dict:
        """Parsed ``settings.json`` — the shared user-settings schema the TUI and the VS Code
        extension both render from. Regenerate with ``python -m galaius.config.schema``."""
        raw = cls.read(cls.SETTINGS)
        if not raw:
            return {}
        try:
            return json.loads(raw)
        except (ValueError, TypeError):
            return {}

    @classmethod
    def grounding_raw(cls) -> str | None:
        """Optional externally-supplied grounding scores — e.g. fetched from an online
        leaderboard — via ``GALAIUS_GROUNDING_JSON`` (raw) or ``GALAIUS_GROUNDING_PATH``
        (file). We never run our own paid eval, so there is no bundled grounding file.
        """
        raw = os.environ.get("GALAIUS_GROUNDING_JSON")
        if raw:
            return raw
        path = os.environ.get("GALAIUS_GROUNDING_PATH")
        if path and Path(path).exists():
            return Path(path).read_text()
        return None
